// Code generated by mocktail; DO NOT EDIT.

package admission

import (
	"context"
	"testing"
	"time"

	"github.com/stretchr/testify/mock"
	"github.com/traefik/hub-agent-kubernetes/pkg/api"
	"github.com/traefik/hub-agent-kubernetes/pkg/platform"
)

// platformClientMock mock of PlatformClient.
type platformClientMock struct{ mock.Mock }

// newPlatformClientMock creates a new platformClientMock.
func newPlatformClientMock(tb testing.TB) *platformClientMock {
	tb.Helper()

	m := &platformClientMock{}
	m.Mock.Test(tb)

	tb.Cleanup(func() { m.AssertExpectations(tb) })

	return m
}

func (_m *platformClientMock) CreatePortal(_ context.Context, req *platform.CreatePortalReq) (*api.Portal, error) {
	_ret := _m.Called(req)

	if _rf, ok := _ret.Get(0).(func(*platform.CreatePortalReq) (*api.Portal, error)); ok {
		return _rf(req)
	}

	_ra0, _ := _ret.Get(0).(*api.Portal)
	_rb1 := _ret.Error(1)

	return _ra0, _rb1
}

func (_m *platformClientMock) OnCreatePortal(req *platform.CreatePortalReq) *platformClientCreatePortalCall {
	return &platformClientCreatePortalCall{Call: _m.Mock.On("CreatePortal", req), Parent: _m}
}

func (_m *platformClientMock) OnCreatePortalRaw(req interface{}) *platformClientCreatePortalCall {
	return &platformClientCreatePortalCall{Call: _m.Mock.On("CreatePortal", req), Parent: _m}
}

type platformClientCreatePortalCall struct {
	*mock.Call
	Parent *platformClientMock
}

func (_c *platformClientCreatePortalCall) Panic(msg string) *platformClientCreatePortalCall {
	_c.Call = _c.Call.Panic(msg)
	return _c
}

func (_c *platformClientCreatePortalCall) Once() *platformClientCreatePortalCall {
	_c.Call = _c.Call.Once()
	return _c
}

func (_c *platformClientCreatePortalCall) Twice() *platformClientCreatePortalCall {
	_c.Call = _c.Call.Twice()
	return _c
}

func (_c *platformClientCreatePortalCall) Times(i int) *platformClientCreatePortalCall {
	_c.Call = _c.Call.Times(i)
	return _c
}

func (_c *platformClientCreatePortalCall) WaitUntil(w <-chan time.Time) *platformClientCreatePortalCall {
	_c.Call = _c.Call.WaitUntil(w)
	return _c
}

func (_c *platformClientCreatePortalCall) After(d time.Duration) *platformClientCreatePortalCall {
	_c.Call = _c.Call.After(d)
	return _c
}

func (_c *platformClientCreatePortalCall) Run(fn func(args mock.Arguments)) *platformClientCreatePortalCall {
	_c.Call = _c.Call.Run(fn)
	return _c
}

func (_c *platformClientCreatePortalCall) Maybe() *platformClientCreatePortalCall {
	_c.Call = _c.Call.Maybe()
	return _c
}

func (_c *platformClientCreatePortalCall) TypedReturns(a *api.Portal, b error) *platformClientCreatePortalCall {
	_c.Call = _c.Return(a, b)
	return _c
}

func (_c *platformClientCreatePortalCall) ReturnsFn(fn func(*platform.CreatePortalReq) (*api.Portal, error)) *platformClientCreatePortalCall {
	_c.Call = _c.Return(fn)
	return _c
}

func (_c *platformClientCreatePortalCall) TypedRun(fn func(*platform.CreatePortalReq)) *platformClientCreatePortalCall {
	_c.Call = _c.Call.Run(func(args mock.Arguments) {
		_req, _ := args.Get(0).(*platform.CreatePortalReq)
		fn(_req)
	})
	return _c
}

func (_c *platformClientCreatePortalCall) OnCreatePortal(req *platform.CreatePortalReq) *platformClientCreatePortalCall {
	return _c.Parent.OnCreatePortal(req)
}

func (_c *platformClientCreatePortalCall) OnDeletePortal(name string, lastKnownVersion string) *platformClientDeletePortalCall {
	return _c.Parent.OnDeletePortal(name, lastKnownVersion)
}

func (_c *platformClientCreatePortalCall) OnUpdatePortal(name string, lastKnownVersion string, req *platform.UpdatePortalReq) *platformClientUpdatePortalCall {
	return _c.Parent.OnUpdatePortal(name, lastKnownVersion, req)
}

func (_c *platformClientCreatePortalCall) OnCreatePortalRaw(req interface{}) *platformClientCreatePortalCall {
	return _c.Parent.OnCreatePortalRaw(req)
}

func (_c *platformClientCreatePortalCall) OnDeletePortalRaw(name interface{}, lastKnownVersion interface{}) *platformClientDeletePortalCall {
	return _c.Parent.OnDeletePortalRaw(name, lastKnownVersion)
}

func (_c *platformClientCreatePortalCall) OnUpdatePortalRaw(name interface{}, lastKnownVersion interface{}, req interface{}) *platformClientUpdatePortalCall {
	return _c.Parent.OnUpdatePortalRaw(name, lastKnownVersion, req)
}

func (_m *platformClientMock) DeletePortal(_ context.Context, name string, lastKnownVersion string) error {
	_ret := _m.Called(name, lastKnownVersion)

	if _rf, ok := _ret.Get(0).(func(string, string) error); ok {
		return _rf(name, lastKnownVersion)
	}

	_ra0 := _ret.Error(0)

	return _ra0
}

func (_m *platformClientMock) OnDeletePortal(name string, lastKnownVersion string) *platformClientDeletePortalCall {
	return &platformClientDeletePortalCall{Call: _m.Mock.On("DeletePortal", name, lastKnownVersion), Parent: _m}
}

func (_m *platformClientMock) OnDeletePortalRaw(name interface{}, lastKnownVersion interface{}) *platformClientDeletePortalCall {
	return &platformClientDeletePortalCall{Call: _m.Mock.On("DeletePortal", name, lastKnownVersion), Parent: _m}
}

type platformClientDeletePortalCall struct {
	*mock.Call
	Parent *platformClientMock
}

func (_c *platformClientDeletePortalCall) Panic(msg string) *platformClientDeletePortalCall {
	_c.Call = _c.Call.Panic(msg)
	return _c
}

func (_c *platformClientDeletePortalCall) Once() *platformClientDeletePortalCall {
	_c.Call = _c.Call.Once()
	return _c
}

func (_c *platformClientDeletePortalCall) Twice() *platformClientDeletePortalCall {
	_c.Call = _c.Call.Twice()
	return _c
}

func (_c *platformClientDeletePortalCall) Times(i int) *platformClientDeletePortalCall {
	_c.Call = _c.Call.Times(i)
	return _c
}

func (_c *platformClientDeletePortalCall) WaitUntil(w <-chan time.Time) *platformClientDeletePortalCall {
	_c.Call = _c.Call.WaitUntil(w)
	return _c
}

func (_c *platformClientDeletePortalCall) After(d time.Duration) *platformClientDeletePortalCall {
	_c.Call = _c.Call.After(d)
	return _c
}

func (_c *platformClientDeletePortalCall) Run(fn func(args mock.Arguments)) *platformClientDeletePortalCall {
	_c.Call = _c.Call.Run(fn)
	return _c
}

func (_c *platformClientDeletePortalCall) Maybe() *platformClientDeletePortalCall {
	_c.Call = _c.Call.Maybe()
	return _c
}

func (_c *platformClientDeletePortalCall) TypedReturns(a error) *platformClientDeletePortalCall {
	_c.Call = _c.Return(a)
	return _c
}

func (_c *platformClientDeletePortalCall) ReturnsFn(fn func(string, string) error) *platformClientDeletePortalCall {
	_c.Call = _c.Return(fn)
	return _c
}

func (_c *platformClientDeletePortalCall) TypedRun(fn func(string, string)) *platformClientDeletePortalCall {
	_c.Call = _c.Call.Run(func(args mock.Arguments) {
		_name := args.String(0)
		_lastKnownVersion := args.String(1)
		fn(_name, _lastKnownVersion)
	})
	return _c
}

func (_c *platformClientDeletePortalCall) OnCreatePortal(req *platform.CreatePortalReq) *platformClientCreatePortalCall {
	return _c.Parent.OnCreatePortal(req)
}

func (_c *platformClientDeletePortalCall) OnDeletePortal(name string, lastKnownVersion string) *platformClientDeletePortalCall {
	return _c.Parent.OnDeletePortal(name, lastKnownVersion)
}

func (_c *platformClientDeletePortalCall) OnUpdatePortal(name string, lastKnownVersion string, req *platform.UpdatePortalReq) *platformClientUpdatePortalCall {
	return _c.Parent.OnUpdatePortal(name, lastKnownVersion, req)
}

func (_c *platformClientDeletePortalCall) OnCreatePortalRaw(req interface{}) *platformClientCreatePortalCall {
	return _c.Parent.OnCreatePortalRaw(req)
}

func (_c *platformClientDeletePortalCall) OnDeletePortalRaw(name interface{}, lastKnownVersion interface{}) *platformClientDeletePortalCall {
	return _c.Parent.OnDeletePortalRaw(name, lastKnownVersion)
}

func (_c *platformClientDeletePortalCall) OnUpdatePortalRaw(name interface{}, lastKnownVersion interface{}, req interface{}) *platformClientUpdatePortalCall {
	return _c.Parent.OnUpdatePortalRaw(name, lastKnownVersion, req)
}

func (_m *platformClientMock) UpdatePortal(_ context.Context, name string, lastKnownVersion string, req *platform.UpdatePortalReq) (*api.Portal, error) {
	_ret := _m.Called(name, lastKnownVersion, req)

	if _rf, ok := _ret.Get(0).(func(string, string, *platform.UpdatePortalReq) (*api.Portal, error)); ok {
		return _rf(name, lastKnownVersion, req)
	}

	_ra0, _ := _ret.Get(0).(*api.Portal)
	_rb1 := _ret.Error(1)

	return _ra0, _rb1
}

func (_m *platformClientMock) OnUpdatePortal(name string, lastKnownVersion string, req *platform.UpdatePortalReq) *platformClientUpdatePortalCall {
	return &platformClientUpdatePortalCall{Call: _m.Mock.On("UpdatePortal", name, lastKnownVersion, req), Parent: _m}
}

func (_m *platformClientMock) OnUpdatePortalRaw(name interface{}, lastKnownVersion interface{}, req interface{}) *platformClientUpdatePortalCall {
	return &platformClientUpdatePortalCall{Call: _m.Mock.On("UpdatePortal", name, lastKnownVersion, req), Parent: _m}
}

type platformClientUpdatePortalCall struct {
	*mock.Call
	Parent *platformClientMock
}

func (_c *platformClientUpdatePortalCall) Panic(msg string) *platformClientUpdatePortalCall {
	_c.Call = _c.Call.Panic(msg)
	return _c
}

func (_c *platformClientUpdatePortalCall) Once() *platformClientUpdatePortalCall {
	_c.Call = _c.Call.Once()
	return _c
}

func (_c *platformClientUpdatePortalCall) Twice() *platformClientUpdatePortalCall {
	_c.Call = _c.Call.Twice()
	return _c
}

func (_c *platformClientUpdatePortalCall) Times(i int) *platformClientUpdatePortalCall {
	_c.Call = _c.Call.Times(i)
	return _c
}

func (_c *platformClientUpdatePortalCall) WaitUntil(w <-chan time.Time) *platformClientUpdatePortalCall {
	_c.Call = _c.Call.WaitUntil(w)
	return _c
}

func (_c *platformClientUpdatePortalCall) After(d time.Duration) *platformClientUpdatePortalCall {
	_c.Call = _c.Call.After(d)
	return _c
}

func (_c *platformClientUpdatePortalCall) Run(fn func(args mock.Arguments)) *platformClientUpdatePortalCall {
	_c.Call = _c.Call.Run(fn)
	return _c
}

func (_c *platformClientUpdatePortalCall) Maybe() *platformClientUpdatePortalCall {
	_c.Call = _c.Call.Maybe()
	return _c
}

func (_c *platformClientUpdatePortalCall) TypedReturns(a *api.Portal, b error) *platformClientUpdatePortalCall {
	_c.Call = _c.Return(a, b)
	return _c
}

func (_c *platformClientUpdatePortalCall) ReturnsFn(fn func(string, string, *platform.UpdatePortalReq) (*api.Portal, error)) *platformClientUpdatePortalCall {
	_c.Call = _c.Return(fn)
	return _c
}

func (_c *platformClientUpdatePortalCall) TypedRun(fn func(string, string, *platform.UpdatePortalReq)) *platformClientUpdatePortalCall {
	_c.Call = _c.Call.Run(func(args mock.Arguments) {
		_name := args.String(0)
		_lastKnownVersion := args.String(1)
		_req, _ := args.Get(2).(*platform.UpdatePortalReq)
		fn(_name, _lastKnownVersion, _req)
	})
	return _c
}

func (_c *platformClientUpdatePortalCall) OnCreatePortal(req *platform.CreatePortalReq) *platformClientCreatePortalCall {
	return _c.Parent.OnCreatePortal(req)
}

func (_c *platformClientUpdatePortalCall) OnDeletePortal(name string, lastKnownVersion string) *platformClientDeletePortalCall {
	return _c.Parent.OnDeletePortal(name, lastKnownVersion)
}

func (_c *platformClientUpdatePortalCall) OnUpdatePortal(name string, lastKnownVersion string, req *platform.UpdatePortalReq) *platformClientUpdatePortalCall {
	return _c.Parent.OnUpdatePortal(name, lastKnownVersion, req)
}

func (_c *platformClientUpdatePortalCall) OnCreatePortalRaw(req interface{}) *platformClientCreatePortalCall {
	return _c.Parent.OnCreatePortalRaw(req)
}

func (_c *platformClientUpdatePortalCall) OnDeletePortalRaw(name interface{}, lastKnownVersion interface{}) *platformClientDeletePortalCall {
	return _c.Parent.OnDeletePortalRaw(name, lastKnownVersion)
}

func (_c *platformClientUpdatePortalCall) OnUpdatePortalRaw(name interface{}, lastKnownVersion interface{}, req interface{}) *platformClientUpdatePortalCall {
	return _c.Parent.OnUpdatePortalRaw(name, lastKnownVersion, req)
}
