// Code generated by mocktail; DO NOT EDIT.

package state

import (
	"context"
	"net/url"
	"testing"
	"time"

	"github.com/stretchr/testify/mock"
	"github.com/traefik/hub-agent-kubernetes/pkg/openapi"
)

// openAPISpecLoaderMock mock of OpenAPISpecLoader.
type openAPISpecLoaderMock struct{ mock.Mock }

// newOpenAPISpecLoaderMock creates a new openAPISpecLoaderMock.
func newOpenAPISpecLoaderMock(tb testing.TB) *openAPISpecLoaderMock {
	tb.Helper()

	m := &openAPISpecLoaderMock{}
	m.Mock.Test(tb)

	tb.Cleanup(func() { m.AssertExpectations(tb) })

	return m
}

func (_m *openAPISpecLoaderMock) Load(_ context.Context, uri *url.URL) (*openapi.Spec, error) {
	_ret := _m.Called(uri)

	if _rf, ok := _ret.Get(0).(func(*url.URL) (*openapi.Spec, error)); ok {
		return _rf(uri)
	}

	_ra0, _ := _ret.Get(0).(*openapi.Spec)
	_rb1 := _ret.Error(1)

	return _ra0, _rb1
}

func (_m *openAPISpecLoaderMock) OnLoad(uri *url.URL) *openAPISpecLoaderLoadCall {
	return &openAPISpecLoaderLoadCall{Call: _m.Mock.On("Load", uri), Parent: _m}
}

func (_m *openAPISpecLoaderMock) OnLoadRaw(uri interface{}) *openAPISpecLoaderLoadCall {
	return &openAPISpecLoaderLoadCall{Call: _m.Mock.On("Load", uri), Parent: _m}
}

type openAPISpecLoaderLoadCall struct {
	*mock.Call
	Parent *openAPISpecLoaderMock
}

func (_c *openAPISpecLoaderLoadCall) Panic(msg string) *openAPISpecLoaderLoadCall {
	_c.Call = _c.Call.Panic(msg)
	return _c
}

func (_c *openAPISpecLoaderLoadCall) Once() *openAPISpecLoaderLoadCall {
	_c.Call = _c.Call.Once()
	return _c
}

func (_c *openAPISpecLoaderLoadCall) Twice() *openAPISpecLoaderLoadCall {
	_c.Call = _c.Call.Twice()
	return _c
}

func (_c *openAPISpecLoaderLoadCall) Times(i int) *openAPISpecLoaderLoadCall {
	_c.Call = _c.Call.Times(i)
	return _c
}

func (_c *openAPISpecLoaderLoadCall) WaitUntil(w <-chan time.Time) *openAPISpecLoaderLoadCall {
	_c.Call = _c.Call.WaitUntil(w)
	return _c
}

func (_c *openAPISpecLoaderLoadCall) After(d time.Duration) *openAPISpecLoaderLoadCall {
	_c.Call = _c.Call.After(d)
	return _c
}

func (_c *openAPISpecLoaderLoadCall) Run(fn func(args mock.Arguments)) *openAPISpecLoaderLoadCall {
	_c.Call = _c.Call.Run(fn)
	return _c
}

func (_c *openAPISpecLoaderLoadCall) Maybe() *openAPISpecLoaderLoadCall {
	_c.Call = _c.Call.Maybe()
	return _c
}

func (_c *openAPISpecLoaderLoadCall) TypedReturns(a *openapi.Spec, b error) *openAPISpecLoaderLoadCall {
	_c.Call = _c.Return(a, b)
	return _c
}

func (_c *openAPISpecLoaderLoadCall) ReturnsFn(fn func(*url.URL) (*openapi.Spec, error)) *openAPISpecLoaderLoadCall {
	_c.Call = _c.Return(fn)
	return _c
}

func (_c *openAPISpecLoaderLoadCall) TypedRun(fn func(*url.URL)) *openAPISpecLoaderLoadCall {
	_c.Call = _c.Call.Run(func(args mock.Arguments) {
		_uri, _ := args.Get(0).(*url.URL)
		fn(_uri)
	})
	return _c
}

func (_c *openAPISpecLoaderLoadCall) OnLoad(uri *url.URL) *openAPISpecLoaderLoadCall {
	return _c.Parent.OnLoad(uri)
}

func (_c *openAPISpecLoaderLoadCall) OnLoadRaw(uri interface{}) *openAPISpecLoaderLoadCall {
	return _c.Parent.OnLoadRaw(uri)
}
